### ISSUE TITLE
Improve error message 

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/decentraland-transactions#33]
If the user reaches the maximum amount of transactions per day. The server answer with 
```
The transaction data is invalid. Check the body of the request.\nError: ${error.message}
```

https://github.com/decentraland/transactions-server/blob/cf4052de58912d38c31ab63ddd924e0875c3a2c1/src/logic/transaction-middleware.ts#L35

**Comment by nicosantangelo** [comment]
Done!
